### ISSUE TITLE
SIFT feature extraction

### ISSUE THREAD

**Issue by swapnil70007** [locked-fg/JFeatureLib#31]
What I have did? 
Using jar JFeatureLib-1.6.3-jar-with-dependencies.jar
and following command 
java -jar JFeatureLib-1.6.3-jar-with-dependencies.jar -D Sift  -d F:\eZen\Swapnil\images -o F:\eZen\Swapnil\op\opp1.csv

same query is working for CEED 

What was expected ?
SIFT values for each image in images folder in opp1.csv file.

What I am getting ?

log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: jFeatureLib.log (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
        at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
        at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java
:207)
        at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
        at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:3
07)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.j
ava:172)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.j
ava:104)
        at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigura
tor.java:842)
        at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigura
tor.java:768)
        at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyC
onfigurator.java:648)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurato
r.java:514)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurato
r.java:580)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionCon
verter.java:526)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.apache.log4j.Logger.getLogger(Logger.java:117)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor.<clinit>(Extractor.java:79
)
0    WARN  [pool-1-thread-2] de.lmu.ifi.dbs.jfeaturelib.features.Sift     - Sift
 Binary not executable: sift.exe
java.io.IOException: Sift Binary not executable: sift.exe
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.<init>(SiftWrapp
er.java:66)
        at de.lmu.ifi.dbs.jfeaturelib.features.Sift.run(Sift.java:114)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor$ExtractionTask.run(Extract
or.java:633)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
0    WARN  [pool-1-thread-3] de.lmu.ifi.dbs.jfeaturelib.features.Sift     - Sift
 Binary not executable: sift.exe
java.io.IOException: Sift Binary not executable: sift.exe
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.<init>(SiftWrapp
er.java:66)
        at de.lmu.ifi.dbs.jfeaturelib.features.Sift.run(Sift.java:114)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor$ExtractionTask.run(Extract
or.java:633)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
0    WARN  [pool-1-thread-4] de.lmu.ifi.dbs.jfeaturelib.features.Sift     - Sift
 Binary not executable: sift.exe
java.io.IOException: Sift Binary not executable: sift.exe
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.<init>(SiftWrapp
er.java:66)
        at de.lmu.ifi.dbs.jfeaturelib.features.Sift.run(Sift.java:114)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor$ExtractionTask.run(Extract
or.java:633)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
0    WARN  [pool-1-thread-1] de.lmu.ifi.dbs.jfeaturelib.features.Sift     - Sift
 Binary not executable: sift.exe
java.io.IOException: Sift Binary not executable: sift.exe
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.<init>(SiftWrapp
er.java:66)
        at de.lmu.ifi.dbs.jfeaturelib.features.Sift.run(Sift.java:114)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor$ExtractionTask.run(Extract
or.java:633)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
16   ERROR [pool-1-thread-2] de.lmu.ifi.dbs.jfeaturelib.utils.Extractor     - In
dex: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor.writeOutput(Extractor.java
:506)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor.access$400(Extractor.java:
77)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor$ExtractionTask.run(Extract
or.java:643)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)

Please help on this

**Comment by locked-fg** [comment]
Hi,
the error says: Binary not executable: siftexe
javaioIOException: Sift Binary not executable: siftexe

Have you downloaded the sift binary and adjusted the properties?
I just realize that this is probably missing in the docs.

Cheers

**Comment by swapnil70007** [comment]
Hi , 
      Thanks for your help and this work. 
      No , I have not downloaded any sift binary.  Frankly I am not getting exactly what is sift binary. Is it executable JAR? and What about adjusting properties ? 
Please elaborate

**Comment by locked-fg** [comment]
Hi,
David Lowe - the original creator of SIFT provides binaries of his algorithm at http://www.cs.ubc.ca/~lowe/keypoints/
JFeatureLib just calls this binary to extract the features. (I tried to reimplement SIFT years ago but never was able to get close to the results of the binary. With the aim of reproducability of research, I decided to call bin binary instead of some weird reimplementation.)

Usually it should be working if you just place the binary in the same directory where you call JFeatureLib. If something won't work, you can set the path to the binary manually in the JFeatureLib properties file which you can unpack from the JAR by 
``` java -jar JFeatureLib-x.x.x-jar-with-dependencies.jar  --unpack-properties   ```.

Hope this works
Franz

**Comment by swapnil70007** [comment]
Hi , 
    Thanks.
     First I downloaded the binary (siftWin32.exe) and put in the same path where jFeatureLib is located. Then also I was getting same exception. 

    After that I open the properties file and noticed that path is set as "sift.exe" which was not matching with name of downloaded binary. 

    After that I tried to edit the properties file but it was impossible for me , so I renamed "siftWin32.exe" to "sift.exe". After renaming the binary it was expected that I will get the results. 
But I am getting following exception:

log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: jFeatureLib.log (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
        at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
        at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java
:207)
        at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
        at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:3
07)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.j
ava:172)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.j
ava:104)
        at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigura
tor.java:842)
        at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigura
tor.java:768)
        at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyC
onfigurator.java:648)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurato
r.java:514)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurato
r.java:580)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionCon
verter.java:526)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.apache.log4j.Logger.getLogger(Logger.java:117)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor.<clinit>(Extractor.java:79
)
0    WARN  [pool-1-thread-4] de.lmu.ifi.dbs.jfeaturelib.features.Sift     - The
pipe is being closed
java.io.IOException: The pipe is being closed
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82
)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.dataToProcess(Si
ftWrapper.java:229)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.getFeatures(Sift
Wrapper.java:130)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.getFeatures(Sift
Wrapper.java:104)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.getFeatures(Sift
Wrapper.java:81)
        at de.lmu.ifi.dbs.jfeaturelib.features.Sift.run(Sift.java:115)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor$ExtractionTask.run(Extract
or.java:633)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
        Suppressed: java.io.IOException: The pipe is being closed
                at java.io.FileOutputStream.writeBytes(Native Method)
                at java.io.FileOutputStream.write(FileOutputStream.java:326)
                at java.io.BufferedOutputStream.write(BufferedOutputStream.java:
122)
                at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream
.java:82)
                at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:
140)
                at java.io.FilterOutputStream.close(FilterOutputStream.java:158)

                at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.dataToPr
ocess(SiftWrapper.java:231)
                ... 10 more
0    ERROR [pool-1-thread-4] de.lmu.ifi.dbs.jfeaturelib.utils.Extractor     - In
dex: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor.writeOutput(Extractor.java
:506)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor.access$400(Extractor.java:
77)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor$ExtractionTask.run(Extract
or.java:643)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
16   WARN  [pool-1-thread-3] de.lmu.ifi.dbs.jfeaturelib.features.Sift     - The
pipe is being closed
java.io.IOException: The pipe is being closed
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82
)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.dataToProcess(Si
ftWrapper.java:229)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.getFeatures(Sift
Wrapper.java:130)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.getFeatures(Sift
Wrapper.java:104)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.getFeatures(Sift
Wrapper.java:81)
        at de.lmu.ifi.dbs.jfeaturelib.features.Sift.run(Sift.java:115)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor$ExtractionTask.run(Extract
or.java:633)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
        Suppressed: java.io.IOException: The pipe is being closed
                at java.io.FileOutputStream.writeBytes(Native Method)
                at java.io.FileOutputStream.write(FileOutputStream.java:326)
                at java.io.BufferedOutputStream.write(BufferedOutputStream.java:
122)
                at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream
.java:82)
                at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:
140)
                at java.io.FilterOutputStream.close(FilterOutputStream.java:158)

                at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.dataToPr
ocess(SiftWrapper.java:231)
                ... 10 more
16   WARN  [pool-1-thread-1] de.lmu.ifi.dbs.jfeaturelib.features.Sift     - The
pipe is being closed
java.io.IOException: The pipe is being closed
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82
)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.dataToProcess(Si
ftWrapper.java:229)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.getFeatures(Sift
Wrapper.java:130)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.getFeatures(Sift
Wrapper.java:104)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.getFeatures(Sift
Wrapper.java:81)
        at de.lmu.ifi.dbs.jfeaturelib.features.Sift.run(Sift.java:115)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor$ExtractionTask.run(Extract
or.java:633)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
        Suppressed: java.io.IOException: The pipe is being closed
                at java.io.FileOutputStream.writeBytes(Native Method)
                at java.io.FileOutputStream.write(FileOutputStream.java:326)
                at java.io.BufferedOutputStream.write(BufferedOutputStream.java:
122)
                at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream
.java:82)
                at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:
140)
                at java.io.FilterOutputStream.close(FilterOutputStream.java:158)

                at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.dataToPr
ocess(SiftWrapper.java:231)
                ... 10 more
32   WARN  [pool-1-thread-2] de.lmu.ifi.dbs.jfeaturelib.features.Sift     - The
pipe is being closed
java.io.IOException: The pipe is being closed
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82
)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:95)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.dataToProcess(Si
ftWrapper.java:229)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.getFeatures(Sift
Wrapper.java:130)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.getFeatures(Sift
Wrapper.java:104)
        at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.getFeatures(Sift
Wrapper.java:81)
        at de.lmu.ifi.dbs.jfeaturelib.features.Sift.run(Sift.java:115)
        at de.lmu.ifi.dbs.jfeaturelib.utils.Extractor$ExtractionTask.run(Extract
or.java:633)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
        Suppressed: java.io.IOException: The pipe is being closed
                at java.io.FileOutputStream.writeBytes(Native Method)
                at java.io.FileOutputStream.write(FileOutputStream.java:326)
                at java.io.BufferedOutputStream.write(BufferedOutputStream.java:
122)
                at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream
.java:82)
                at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:
140)
                at java.io.FilterOutputStream.close(FilterOutputStream.java:158)

                at de.lmu.ifi.dbs.jfeaturelib.features.sift.SiftWrapper.dataToPr
ocess(SiftWrapper.java:231)
                ... 10 more

I am using win 8 64 bit , jdk 8. Is it working at your site ???

**Comment by locked-fg** [comment]
Your error message says "java.io.FileNotFoundException: jFeatureLib.log (Access is denied)". 

Maybe you had two instances of JFeatureLib running? (Btw yes it's running here.)  or some program kept an old file handle. Have you tried in another directory or after rebooting (the easiest way to get rid of all stale file handles). 

As I dare say that it is not a bug, you could also ask at the Google group. There are a couple of people reading there. Maybe someone else can help as well. Here you just rely on me.

**Comment by swapnil70007** [comment]
When I execute command for CEDD which gives me result in specified file at that scenario also I get same exception "java.io.FileNotFoundException: jFeatureLib.log (Access is denied)". 
So I think that is not the issue. 

I tried rebooting  and but didn't worked. 
As per your suggestion I am posting this to google group. 
Thanks.

**Comment by locked-fg** [comment]
CEDD works perfectly for me. But I can confirm that SIFT has some Problems with the pipes.
The followup call for help is here: https://groups.google.com/forum/#!topic/jfeaturelib/JoBqRWpEfmQ

**Comment by luismilanooliveira** [comment]
@swapnil70007 That "(Access is denied)" error is most likely about your program being run inside a directory where it doesn't have permissions to read/write files.
